package com.wenance.coreapi.model;

import java.util.Arrays;

import com.wenance.coreapi.v2.exception.UnknownStatusException;

public enum Status {

    RECEIVED,
    CANCELED,
    OPPORTUNITY_CREATE_INIT,
    OPPORTUNITY_CREATE_OK,
    OPPORTUNITY_CREATE_FAIL,
    OPPORTUNITY_UPDATE_PENDING,
    OPPORTUNITY_UPDATE_INIT,
    OPPORTUNITY_UPDATE_OK,
    OPPORTUNITY_UPDATE_FAIL,
    SIGNATURE_NOTIFICATION_PENDING,
    SIGNATURE_NOTIFICATION_INIT,
    SIGNATURE_NOTIFICATION_OK,
    SIGNATURE_NOTIFICATION_FAIL,
    DISBURSE_INIT,
    DISBURSE_OK,
    DISBURSE_FAIL,
    SIGNATURE_INIT,
    QUEUE_REMINDER_INIT,
    REMIND_CONTRACT_INIT,
    REMIND_CONTRACT_OK,
    REMIND_CONTRACT_FAIL,
    REMIND_ONBOARDING_INIT,
    REMIND_ONBOARDING_OK,
    REMIND_ONBOARDING_FAIL,
    BLACKLIST_INSERT_INIT,
    BLACKLIST_INSERT_OK,
    BLACKLIST_NOTIFICATION_INIT,
    BLACKLIST_NOTIFICATION_PENDING,
    BLACKLIST_NOTIFICATION_OK,
    BLACKLIST_NOTIFICATION_FAIL,
    BLACKLIST_INSERT_FAIL,
    DOC_CRM_VALIDATION_OK,
    DOC_CRM_VALIDATION_FAIL,
    OFFER_GENERATED,
    IDENTITY_VALIDATION_FAIL_NOTIFICATION_INIT,
    IDENTITY_VALIDATION_FAIL_NOTIFICATION_OK,
    IDENTITY_VALIDATION_FAIL_NOTIFICATION_FAIL
    ;

    public static Status of(String value) {
        return Arrays.stream(values())
                .filter(v -> v.name().equalsIgnoreCase(value))
                .findFirst()
                .orElseThrow(() -> new UnknownStatusException(value));
    }

}
